### ISSUE TITLE
"Import content" and other objects giving error

### ISSUE THREAD

**Issue by dgolveira** [mozilla/hubs-compose#49]
Guys, I'm not able to add any external content through the admin. I am experiencing the following errors
Reticulum Erro:
![Screenshot_1](https://github.com/mozilla/hubs-compose/assets/35613079/9b8ae4a8-5c11-4a10-9eac-0fade2bfe9d7)
Admin console error
![Screenshot_2](https://github.com/mozilla/hubs-compose/assets/35613079/4f96d5fb-d758-463b-a442-fa5235c17d1c)
Spoke erro:
![image](https://github.com/mozilla/hubs-compose/assets/35613079/32b02ff5-268f-4ab3-b969-960f755a40d3)

All of this is running on my local network as proposed by this environment.

**Comment by dgolveira** [comment]
More logs from reticulim 

[notice] TLS :server: In state :certify received CLIENT ALERT: Fatal - Certificate Unknown

[info] GET /https://hubs.mozilla.com/api/v1/avatars/ULbm8t9
[debug] Processing with RetWeb.PageController
  Parameters: [UNFETCHED]
  Pipelines: [:secure_headers, :parsed_body, :browser]
[info] Sent 500 in 480ms
[error] #PID<0.2167.105> running RetWeb.Endpoint (connection #PID<0.2148.105>, stream id 1) terminated
Server: hubs-proxy.local:4000 (https)
Request: GET /https://hubs.mozilla.com/api/v1/avatars/ULbm8t9
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {"", %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "hubs-proxy.local", method: "GET", owner: #PID<0.2167.105>, params: %{"path" => ["https:", "hubs.mozilla.com", "api", "v1", "avatars", "ULbm8t9"]}, path_info: ["https:", "hubs.mozilla.com", "api", "v1", "avatars", "ULbm8t9"], path_params: %{"path" => ["https:", "hubs.mozilla.com", "api", "v1", "avatars", "ULbm8t9"]}, port: 4000, private: %{RetWeb.Router => {[], %{Absinthe.Plug => [], Absinthe.Plug.GraphiQL => ["graphiql"], RetWeb.Plugs.ItaProxy => [], RetWeb.Plugs.PostgrestProxy => []}}, :before_send => [#Function<1.28559294/1 in Plug.Logger.call/2>, #Function<0.66660011/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>], :phoenix_endpoint => RetWeb.Endpoint, :phoenix_format => "html", :phoenix_layout => false, :phoenix_router => RetWeb.Router}, query_params: %{}, query_string: "", remote_ip: {10, 11, 12, 6}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "*/*"}, {"accept-encoding", "gzip, deflate, br, zstd"}, {"accept-language", "en-US,en;q=0.9"}, {"origin", "https://hubs.local:4000"}, {"referer", "https://hubs.local:4000/"}, {"sec-ch-ua", "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\""}, {"sec-ch-ua-mobile", "?0"}, {"sec-ch-ua-platform", "\"Windows\""}, {"sec-fetch-dest", "empty"}, {"sec-fetch-mode", "cors"}, {"sec-fetch-site", "cross-site"}, {"user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}], request_path: "/https://hubs.mozilla.com/api/v1/avatars/ULbm8t9", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "F8BoPKdjZuAz2UoAA0zD"}, {"access-control-allow-origin", "*"}, {"access-control-expose-headers", ""}, {"access-control-allow-credentials", "true"}, {"vary", "Origin"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-permitted-cross-domain-policies", "none"}, {"cross-origin-window-policy", "deny"}, {"content-security-policy", "base-uri 'none'; child-src 'self' blob: ; connect-src 'self' blob: data: https://api.github.com https://bh4d9od16a-3.algolianet.com https://cdn.aframe.io https://dpdb.webvr.rocks https://www.google-analytics.com https://www.youtube.com https://fonts.gstatic.com https://hubs-assets.local https://hubs-proxy.local:4000 https://hubs.local:8080 https://sentry.prod.mozaws.net https://localhost:4000 https://localhost:8080 https://hubs.local:4000 https://hubs.local:8080 https://hubs.local:3000 https://hubs.local:8989 https://hubs.local:9090 https://hubs-proxy.local:4000 https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io https://localhost:4000 https://localhost:8080 wss://localhost:4000 https://hubs.local:4000 https://hubs.local:8080 wss://hubs.local:4000 wss://hubs.local:8080 wss://hubs.local:8989 wss://hubs.local:9090 wss://hubs.local:4000 wss://hubs.local:8080 https://hubs.local:8080 https://hubs.local:8080 wss://hubs.local:8080 https://www.mozilla.org https://hubs-link.local:4000 https://hubs.local:4000 wss://hubs.local:4443 wss://hubs.local:4000 https://hubs.local:4443 wss://hubs.local:4443 https://hubs.local:4443 https://hubs.local:4000 https://hubs-proxy.local:4000 https://raw.githubusercontent.com; default-src 'none'; font-src 'self' https://cdn.aframe.io https://cdn.jsdelivr.net https://fonts.googleapis.com https://fonts.gstatic.com https://hubs-assets.local https://hubs-proxy.local:4000 https://localhost:4000 https://localhost:8080 https://hubs.local:4000 https://hubs.local:8080 https://hubs.local:3000 https://hubs.local:8989 https://hubs.local:9090 https://hubs-proxy.local:4000 https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io https://hubs.local:4000; form-action 'self' ; frame-src 'self' https://docs.google.com https://player.vimeo.com https://www.youtube.com ; img-src 'self' blob: data: https://cdn.aframe.io https://cdn.jsdelivr.net https://user-images.githubusercontent.com https://www.google-analytics.com https://www.youtube.com https://hubs-assets.local https://hubs-proxy.local:4000 https://localhost:4000 https://localhost:8080 https://hubs.local:4000 https://hubs.local:8080 https://hubs.local:3000 https://hubs.local:8989 https://hubs.local:9090 https://hubs-proxy.local:4000 https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io https://hubs.local:4000 https://hubs-proxy.local:4000; manifest-src 'self' https://localhost:4000 https://localhost:8080 https://hubs.local:4000 https://hubs.local:8080 https://hubs.local:3000 https://hubs.local:8989 https://hubs.local:9090 https://hubs-proxy.local:4000 https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io; media-src 'self' *.googlevideo.com blob: data: https://www.youtube.com https://hubs-assets.local https://hubs-proxy.local:4000 https://localhost:4000 https://localhost:8080 https://hubs.local:4000 https://hubs.local:8080 https://hubs.local:3000 https://hubs.local:8989 https://hubs.local:9090 https://hubs-proxy.local:4000 https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io https://hubs.local:4000 https://hubs-proxy.local:4000; script-src 'self' blob: 'sha256-/S6PM16MxkmUT7zJN2lkEKFgvXR7yL4Z8PCrRrFu4Q8=' 'sha256-MIpWPgYj31kCgSUFc0UwHGQrV87W6N5ozotqfxxQG0w=' 'sha256-ViVvpb0oYlPAp7R8ZLxlNI6rsf7E7oz8l1SgCIXgMvM=' 'sha256-buF6N8Z4p2PuaaeRUjm7mxBpPNf4XlCT9Fep83YabbM=' 'sha256-foB3G7vO68Ot8wctsG3OKBQ84ADKVinlnTg9/s93Ycs=' 'sha256-g0j42v3Wo/ohUAMR/t0EuObDSEkx1rZ3lv45fUaNmYs=' 'sha256-hsbRcgUBASABDq7qVGVTpbnWq/ns7B+ToTctZFJXYi8=' 'unsafe-eval' https://aframe.io https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js https://s.ytimg.com https://ssl.google-analytics.com https://www.google-analytics.com https://www.youtube.com https://hubs-assets.local https://localhost:4000 https://localhost:8080 https://hubs.local:4000 https://hubs.local:8080 https://hubs.local:3000 https://hubs.local:898" <> ...}], scheme: :https, script_name: [], secret_key_base: :..., state: :unset, status: nil}}
        (hackney 1.18.1) /code/deps/hackney/src/hackney_request.erl:322: :hackney_request.handle_body/4
        (hackney 1.18.1) /code/deps/hackney/src/hackney_request.erl:87: :hackney_request.perform/2
        (hackney 1.18.1) /code/deps/hackney/src/hackney.erl:378: :hackney.send_request/2
        (httpoison 1.6.2) lib/httpoison/base.ex:796: HTTPoison.Base.request/6
        (reverse_proxy_plug 2.4.0) lib/reverse_proxy_plug/http_client/adapters/httpoison.ex:15: ReverseProxyPlug.HTTPClient.Adapters.HTTPoison.request/1
        (ret 1.0.0) lib/ret_web/controllers/page_controller.ex:731: RetWeb.PageController.cors_proxy/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (ret 1.0.0) lib/plug/error_handler.ex:80: RetWeb.Router.call/2
        (ret 1.0.0) lib/ret_web/endpoint.ex:1: RetWeb.Endpoint.plug_builder_call/2
        (ret 1.0.0) lib/plug/debugger.ex:136: RetWeb.Endpoint."call (overridable 3)"/2
        (ret 1.0.0) lib/ret_web/endpoint.ex:1: RetWeb.Endpoint."call (overridable 4)"/2
        (ret 1.0.0) lib/ret_web/endpoint.ex:1: RetWeb.Endpoint.call/2
        (phoenix 1.5.14) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /code/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /code/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy (truncated)
